language: python

python:
  - "3.8"
  - "3.9"

install:
  - python setup.py install

script:
  # Run the tests
  - cd ..; nosetests --with-coverage --cover-package=SBMate SBMate/tests

after_success:
  - coveralls