language: python

python:
  - "3.8"
  - "3.9"

install:
    - pip install networkx
    - pip install nose
    - pip install numpy
    - pip install pandas
    - pip install python-libsbml
    - pip install requests

script:
  # Run the tests
  - cd ..; nosetests SBMate/tests