language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install Cython
  - python setup.py install

script:
  # Run the tests
  - cd ..; nosetests --with-coverage SBMate/tests

after_success:
  - coveralls